name = "GenOpt"
uuid = "f2c049d8-7489-4223-990c-4f1c121a4cde"
version = "0.1.0"
authors = ["Beno√Æt Legat <benoit.legat@gmail.com>"]

[deps]
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
ExaModels = "0.9"
JuMP = "1.29"
MathOptInterface = "1.46"
